version: "3"

services:
  app:
    build: .
    container_name: microservice-videos-app
    volumes:
      - .:/var/www
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: microservice-videos-nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
